language: csharp
sudo: required
services:
  - docker

mono:
  - 4.0.0

before_install:
  # set up dotnet set up
  - curl -sSL https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.sh | DNX_BRANCH=1.0.0-rc1-final
    sh && source ~/.dnx/dnvm/dnvm.sh
  - dnvm upgrade
  - dnvm install 1.0.0-rc1-update1 -arch x64 -p
  - dnvm use default
  # set up aws cli
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin

install:
  # docker build webservice
  - docker build -t bootstrap-webservice ./WebService
  # docker build workerservice
  - docker build -t bootstrap-workerservice ./WorkerService

script:
  # WebService test
  - dnu restore ./WebService.UnitTests/project.json
  - dnx -p ./WebService.UnitTests/project.json test -parallel none
  # - run docker container
  # - run any integration tests on the container using scripts
  # WorkerService test
  - dnu restore ./WorkerService.UnitTests/project.json
  - dnx -p ./WorkerService.UnitTests/project.json test -parallel none
  # - run docker container
  # - run any integration tests on the container using scripts

branches:
  only:
  - master

after_success:
  - $(aws ecr get-login --region us-east-1) # does docker login
  # webservice docker push
  - docker tag bootstrap-webservice:$TRAVIS_JOB_ID
  - docker push 047651431481.dkr.ecr.us-east-1.amazonaws.com/bootstrap-webservice:$TRAVIS_JOB_ID
  # workerservice docker push
  - docker tag bootstrap-workerservice:$TRAVIS_JOB_ID
  - docker push 047651431481.dkr.ecr.us-east-1.amazonaws.com/bootstrap-workerservice:$TRAVIS_JOB_ID
