language: csharp
sudo: required
services:
- docker
mono:
- 4.0.0
before_install:
- curl -sSL https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.sh | DNX_BRANCH=1.0.0-rc1-final
  sh && source ~/.dnx/dnvm/dnvm.sh
- dnvm upgrade
- dnvm install 1.0.0-rc1-update1 -arch x64 -p
- dnvm use default
- pip install --user awscli
- export PATH=$PATH:$HOME/.local/bin
install:
- docker build -t bootstrap-webservice ./WebService
- docker build -t bootstrap-workerservice ./WorkerService
script:
- dnu restore ./WebService.UnitTests/project.json
- dnx -p ./WebService.UnitTests/project.json test
- dnu restore ./WorkerService.UnitTests/project.json
- dnx -p ./WorkerService.UnitTests/project.json test
branches:
  only:
  - master
deploy:
- "$(aws ecr get-login --region us-east-1)"
- docker tag bootstrap-webservice:$TRAVIS_JOB_ID
- docker push 047651431481.dkr.ecr.us-east-1.amazonaws.com/bootstrap-webservice:$TRAVIS_JOB_ID
- docker tag bootstrap-workerservice:$TRAVIS_JOB_ID
- docker push 047651431481.dkr.ecr.us-east-1.amazonaws.com/bootstrap-workerservice:$TRAVIS_JOB_ID
